#cloud-config
runcmd:
  - sh -c 'echo deb https://apt.buildkite.com/buildkite-agent stable main > /etc/apt/sources.list.d/buildkite-agent.list'
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 32A37959C2FA5C3C99EFBC32A79206696452D198
  - apt-get update
  - apt-get install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y buildkite-agent docker-ce
  - snap install doctl
  - snap connect doctl:dot-docker
  - mkdir ~/.config
  - doctl auth init --access-token DOCTL_API_TOKEN
  - sed -i "s/xxx/BUILDKITEKEY/g" /etc/buildkite-agent/buildkite-agent.cfg
  - systemctl enable buildkite-agent
  - systemctl start buildkite-agent