#cloud-config
runcmd:
  - sh -c 'echo deb https://apt.buildkite.com/buildkite-agent stable main > /etc/apt/sources.list.d/buildkite-agent.list'
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 32A37959C2FA5C3C99EFBC32A79206696452D198
  - apt-get update
  - apt-get install -y buildkite-agent
  - snap install doctl
  - snap connect doctl:dot-docker
  - mkdir ~/.config
  - doctl auth init --access-token DOCTL_API_TOKEN
  - sed -i "s/xxx/BUILDKITEKEY/g" /etc/buildkite-agent/buildkite-agent.cfg
  - systemctl enable buildkite-agent
  - systemctl start buildkite-agent